### ISSUE TITLE
Issue Regarding Submission Format

### ISSUE THREAD

**Issue by Byeol-Haneul** [SNU-ARC/2024_spring_sysprog_Lab3#39]
I found out that the wiki is misleading due to a small typo 

`tar -cvf 2024-12345.tar src/memmrg.c 2024-12345.pdf
src/memmrg.c
2024-12345.pdf`

where **memmrg.c** should be corrected to **memmgr.c**. Otherwise, the compressed file would leave out the source file, without producing error (despite printing the warning message). For those who just copied and pasted the command line, I think you might want to double-check your tar file. 

Moreover, I found out that after extracting with `tar -xvf 2024-12345.tar`, the structure of the directory is,

```
2024-12345/
    ├── 2024-12345.pdf
    └── src/
        └── memmgr.c
```

Is it correct that we maintain the source code in a separate directory `src`?

**Comment by kwonsw055** [comment]
Thanks for the typo report!
As discussed in [Lab 2 issue no.9](https://github.com/SNU-ARC/2024_spring_sysprog_Lab2/issues/9), inside the tar file, having the source code in a separate `src` directory is correct.
